In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
plt.style.available

['Solarize_Light2',
 '_classic_test_patch',
 '_mpl-gallery',
 '_mpl-gallery-nogrid',
 'bmh',
 'classic',
 'dark_background',
 'fast',
 'fivethirtyeight',
 'ggplot',
 'grayscale',
 'petroff10',
 'seaborn-v0_8',
 'seaborn-v0_8-bright',
 'seaborn-v0_8-colorblind',
 'seaborn-v0_8-dark',
 'seaborn-v0_8-dark-palette',
 'seaborn-v0_8-darkgrid',
 'seaborn-v0_8-deep',
 'seaborn-v0_8-muted',
 'seaborn-v0_8-notebook',
 'seaborn-v0_8-paper',
 'seaborn-v0_8-pastel',
 'seaborn-v0_8-poster',
 'seaborn-v0_8-talk',
 'seaborn-v0_8-ticks',
 'seaborn-v0_8-white',
 'seaborn-v0_8-whitegrid',
 'tableau-colorblind10']

In [5]:
sns.set(style='whitegrid')
plt.rcParams['figure.figsize']=(15,10)

In [6]:
df=pd.read_csv('DATASET/UberDataset.csv')

In [7]:
df.head(3)

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,01-01-2016 21:11,01-01-2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,01-02-2016 01:25,01-02-2016 01:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,01-02-2016 20:25,01-02-2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies

In [8]:
df.shape

(1156, 7)

In [9]:
df.tail()

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
1151,12/31/2016 13:24,12/31/2016 13:42,Business,Kar?chi,Unknown Location,3.9,Temporary Site
1152,12/31/2016 15:03,12/31/2016 15:38,Business,Unknown Location,Unknown Location,16.2,Meeting
1153,12/31/2016 21:32,12/31/2016 21:50,Business,Katunayake,Gampaha,6.4,Temporary Site
1154,12/31/2016 22:08,12/31/2016 23:51,Business,Gampaha,Ilukwatta,48.2,Temporary Site
1155,Totals,NaN,NaN,NaN,NaN,12204.7,NaN

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   START_DATE  1156 non-null   object
 1   END_DATE    1155 non-null   object
 2   CATEGORY    1155 non-null   object
 3   START       1155 non-null   object
 4   STOP        1155 non-null   object
 5   MILES       1156 non-null   float64
 6   PURPOSE     653 non-null    object
dtypes: float64(1), object(6)
memory usage: 63.3+ KB

In [11]:
df.describe()

              MILES
count   1156.000000
mean      21.115398
std      359.299007
min        0.500000
25%        2.900000
50%        6.000000
75%       10.400000
max    12204.700000

In [12]:
df.describe().T  #Transpose row to column and column to row

        count       mean         std  min  25%  50%   75%      max
MILES  1156.0  21.115398  359.299007  0.5  2.9  6.0  10.4  12204.7

In [13]:
df.describe(include='object')

             START_DATE         END_DATE  CATEGORY START  STOP  PURPOSE
count              1156             1155      1155  1155  1155      653
unique             1155             1154         2   177   188       10
top     6/28/2016 23:34  6/28/2016 23:59  Business  Cary  Cary  Meeting
freq                  2                2      1078   201   203      187

In [14]:
df.describe(include='object').T

           count unique              top  freq
START_DATE  1156   1155  6/28/2016 23:34     2
END_DATE    1155   1154  6/28/2016 23:59     2
CATEGORY    1155      2         Business  1078
START       1155    177             Cary   201
STOP        1155    188             Cary   203
PURPOSE      653     10          Meeting   187

In [15]:
df.isnull().sum()

START_DATE      0
END_DATE        1
CATEGORY        1
START           1
STOP            1
MILES           0
PURPOSE       503
dtype: int64

In [16]:
df.isnull()

      START_DATE  END_DATE  CATEGORY  START   STOP  MILES  PURPOSE
0          False     False     False  False  False  False    False
1          False     False     False  False  False  False     True
2          False     False     False  False  False  False    False
3          False     False     False  False  False  False    False
4          False     False     False  False  False  False    False
...          ...       ...       ...    ...    ...    ...      ...
1151       False     False     False  False  False  False    False
1152       False     False     False  False  False  False    False
1153       False     False     False  False  False  False    False
1154       False     False     False  False  False  False    False
1155       False      True      True   True   True  False     True

[1156 rows x 7 columns]

In [17]:
df.dtypes

START_DATE     object
END_DATE       object
CATEGORY       object
START          object
STOP           object
MILES         float64
PURPOSE        object
dtype: object

In [18]:
(df.isnull().sum()/len(df))*100  #missing values percentaage

START_DATE     0.000000
END_DATE       0.086505
CATEGORY       0.086505
START          0.086505
STOP           0.086505
MILES          0.000000
PURPOSE       43.512111
dtype: float64

In [19]:
df['CATEGORY'].unique()

array(['Business', 'Personal', nan], dtype=object)

In [20]:
df['CATEGORY'].nunique()

2

In [21]:
df['CATEGORY']=df['CATEGORY'].astype("category")

In [22]:
df.dtypes

START_DATE      object
END_DATE        object
CATEGORY      category
START           object
STOP            object
MILES          float64
PURPOSE         object
dtype: object

In [23]:
df.shape

(1156, 7)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   START_DATE  1156 non-null   object
 1   END_DATE    1155 non-null   object
 2   CATEGORY    1155 non-null   category
 3   START       1155 non-null   object
 4   STOP        1155 non-null   object
 5   MILES       1156 non-null   float64
 6   PURPOSE     653 non-null    object
dtypes: category(1), float64(1), object(5)
memory usage: 55.6+ KB

In [25]:
df['START_DATE'].nunique()

1155

In [26]:
df.columns

Index(['START_DATE', 'END_DATE', 'CATEGORY', 'START', 'STOP', 'MILES',
       'PURPOSE'],
      dtype='object')

In [27]:
df.head(3)

,START_DATE,END_DATE,CATEGORY,START,STOP,MILES,PURPOSE
0,01-01-2016 21:11,01-01-2016 21:17,Business,Fort Pierce,Fort Pierce,5.1,Meal/Entertain
1,01-02-2016 01:25,01-02-2016 01:37,Business,Fort Pierce,Fort Pierce,5.0,NaN
2,01-02-2016 20:25,01-02-2016 20:38,Business,Fort Pierce,Fort Pierce,4.8,Errand/Supplies

In [35]:
df['START_DATE']=pd.to_datetime(df['START_DATE'], format="mixed")
df['END_DATE']=pd.to_datetime(df['END_DATE'], format="mixed")

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   START_DATE  421 non-null    datetime64[ns]
 1   END_DATE    420 non-null    datetime64[ns]
 2   CATEGORY    1155 non-null   category
 3   START       1155 non-null   object
 4   STOP        1155 non-null   object
 5   MILES       1156 non-null   float64
 6   PURPOSE     653 non-null    object
dtypes: category(1), datetime64[ns](2), float64(1), object(3)
memory usage: 55.6+ KB